[project]
name = "aiml-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14.2"
dependencies = [
    "numpy>=2.4.1",
    "pandas>=2.3.3",
    "tdqm>=0.0.1",
]
